apiVersion: v1
kind: Pod
metadata:
  name: fale-mais-front
  labels:
    app: fale-mais-front
spec:
  containers:
    - name: fale-mais-front
      image: douglasaugustojunior/fale-mais-front:latest
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: fale-mais-front-configmap
